[15.0][MIG] sale_coupon_criteria_order_based: Migration to version 15.0
OCA/sale-promotion pull request #114
Opened 2023-02-20 11:22 UTC by pilarvargas-tecnativa

cc @Tecnativa TT38306

@chienandalu @ernestotejeda please review :)

2023-02-20 12:24 UTC, chienandalu requested changes

2023-02-20 12:24 UTC, chienandalu commented on sale_coupon_criteria_order_based/readme/DESCRIPTION.rst
> +the Sales Order values.
```suggestion
This module adds an option to configure your coupon conditions based on
the Sales Order values.
```

2023-02-21 07:57 UTC, ernestotejeda approved these changes

2023-02-21 10:00 UTC, chienandalu approved these changes
Thanks! :+1:

2023-02-21 10:38 UTC, pedrobaeza commented
/ocabot migration sale_coupon_criteria_order_based

2023-02-21 10:39 UTC, pedrobaeza commented
/ocabot merge nobump

2023-02-21 10:46 UTC, merged