[15.0][MIG] sale_coupon_portal: Migration to version 15.0
OCA/sale-promotion pull request #131
Opened 2023-04-26 13:47 UTC by stefan-tecnativa

cc @Tecnativa TT42513

@chienandalu please review!

2023-04-28 23:48 UTC, pedrobaeza commented
/ocabot migration sale_coupon_portal

2023-04-28 23:50 UTC, pedrobaeza commented
This should be renamed to `coupon_portal` and change terminology across the XMLs.

2023-05-04 11:07 UTC, chienandalu requested changes

2023-05-04 11:07 UTC, chienandalu commented on coupon_portal/i18n/sale_coupon_portal.pot
You should regenerate translations

2023-05-04 13:12 UTC, chienandalu approved these changes

2023-05-05 05:58 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-05-05 07:58 UTC, merged