[FIX] Enable the posibility of adding more products of a gifted product as new line in the order.
OCA/sale-promotion pull request #31
Opened 2021-10-25 09:33 UTC by alvaro-domatix

I think this is a posible solution for the question I posed [here](https://github.com/OCA/sale-promotion/issues/30).

This code allows to add as new lines in the order more units of a product that has been gifted for some promotion.

2021-10-25 11:01 UTC, chienandalu reviewed
The fix looks good, but a new module should be made:

- This module doesn't depend on `website_sale_coupon`, so this method isn't available.
- It will happen with `sale_coupon_multiplier_free_product` which uses the same kind of discount lines.

2021-10-25 11:25 UTC, alvaro-domatix commented
Alright! I'll do it. Any module name suggestion? @chienandalu

2021-10-25 11:27 UTC, chienandalu commented
@pedrobaeza uses to be more inspired with names than me :sweat_smile:

2021-10-25 11:28 UTC, pedrobaeza commented
`website_sale_coupon_multi_gift` should be the obvious choose.

2021-10-25 11:32 UTC, chienandalu commented
It's not only compatibility with `sale_coupon_multi_gift` but with `sale_coupon_multiplier_free_product` as well (or any other using that kind of rewads)

2021-10-25 11:35 UTC, pedrobaeza commented
Uhm, `website_sale_coupon_reward_line_discriminant`? Anyways, shouldn't this be done at `website_sale_coupon` level and it's a bug?

2021-10-25 11:56 UTC, alvaro-domatix commented
> Uhm, `website_sale_coupon_reward_line_discriminant`? Anyways, shouldn't this be done at `website_sale_coupon` level and it's a bug?

No because in website_sale_coupon when you gift one product of your shop, it adds one order line for the product (where you can change the quantity) and one for the gift. multi_gift module adds one unique line with 100%discount so you can't modify the quantity as it is a "reward_line".

I will use website_sale_coupon_reward_line_discriminant as the name if you both agree.

2021-10-25 11:58 UTC, chienandalu commented
:+1:

2021-10-25 13:45 UTC, chienandalu approved these changes

2021-10-25 13:45 UTC, chienandalu commented on website_sale_coupon_reward_line_discriminant/__manifest__.py
> +    "depends": ["website_sale"],
```suggestion
    "depends": ["website_sale_coupon"],
```

2021-10-25 13:45 UTC, chienandalu commented on website_sale_coupon_reward_line_discriminant/models/sale_order.py
> +        lines = super(SaleOrder, self)._cart_find_product_line(
```suggestion
        lines = super()._cart_find_product_line(
```

2021-10-25 13:45 UTC, chienandalu commented on website_sale_coupon_reward_line_discriminant/readme/DESCRIPTION.rst
> +This module allows to modify quantity of a sale order line that are a product gift reward adding a new line to manage not reward quantities.
Add some background on the modules that would benefit from this technical addons

2021-10-26 06:51 UTC, alvaro-domatix commented on website_sale_coupon_reward_line_discriminant/models/sale_order.py
> +        lines = super(SaleOrder, self)._cart_find_product_line(
I made all 3 suggested changes. But I would like to ask why this super is better than the other? Or it's just not better, just cleaner?

2021-10-26 06:54 UTC, pedrobaeza commented on website_sale_coupon_reward_line_discriminant/models/sale_order.py
> +        lines = super(SaleOrder, self)._cart_find_product_line(
It's a cleaner syntax since Python 3

2022-03-01 11:15 UTC, chienandalu commented
@alvaro-domatix Are you still on this?

2022-03-01 11:31 UTC, alvaro-domatix commented
Yes, if it is everything fine and I just need to do the test I will do it.

2022-04-07 08:39 UTC, alvaro-domatix commented
Hello @chienandalu, I'd like to know if the pre-commit failing has something to do with our code or how to fix it.

2022-04-08 06:21 UTC, alvaro-domatix commented
Didn't want to close this PR, can be reopened or do I have to open a new one? @chienandalu @pedrobaeza

2022-04-13 11:24 UTC, alvaro-domatix commented
How can we relaunch the checks? @chienandalu @pedrobaeza

2022-04-13 11:26 UTC, pedrobaeza commented
do rebase and force push

2022-09-29 06:41 UTC, chienandalu approved these changes

2022-09-29 06:47 UTC, pedrobaeza requested changes
Very few formal questions. Apart from the comments inline, please name the commit properly:

```
[ADD] sale_coupon_reward_line_driscriminant

Enable the possibility of adding more products of a gifted product as new line
in the order.
```

2022-09-29 06:47 UTC, pedrobaeza commented on website_sale_coupon_reward_line_discriminant/readme/CONTRIBUTORS.rst
> +* `Tecnativa <https://www.tecnativa.com>`_:
No need to include us, as this module is yours.

2022-09-29 06:47 UTC, pedrobaeza commented on website_sale_coupon_reward_line_discriminant/readme/DESCRIPTION.rst
> +This module is useful when used in conjunction with others like 'sale_coupon_multi_gift' or 'sale_coupon_multiplier_free_product', allowing you to make offers and the customer to buy more if they wan
Leave an empty line in between for proper recognition of a new paragraph.

2022-10-30 12:42 UTC, closed without merging