[14.0][ADD] sale_coupon_sale_order_based
OCA/sale-promotion pull request #54
Opened 2022-05-07 11:30 UTC by isserver1

Sales Order based domain for Sales Coupon

2022-05-08 13:53 UTC, elvise commented
@sbidoul can you check what happen here with the runboat? 

thanks in advance for your support

2022-05-08 16:11 UTC, sbidoul commented
Runboat was enjoying a sunny week-end :) Nah, actually there was something super weird going on: https://github.com/OCA/oca-ci/issues/29, so I had to shut it down to recover.

I manually triggered a build for this PR.

2022-05-08 16:29 UTC, elvise commented
@sbidoul thanks do much man! :)

2022-05-09 07:57 UTC, francesco-ooops approved these changes
Functional review ok!

2022-05-09 08:10 UTC, elvise approved these changes
LGTM!

2022-05-13 09:59 UTC, francesco-ooops commented
@chienandalu any opinion on this one?

2022-05-17 15:38 UTC, francesco-ooops commented
@OCA/crm-sales-marketing-maintainers

2022-05-18 16:24 UTC, elvise commented
@OCA/crm-sales-marketing-maintainers  is there a good soul who can make a review? :)

2022-05-20 11:06 UTC, elvise commented
@rousseldenis would be great if can check this PR :)

2022-05-23 19:29 UTC, elvise commented
@pedrobaeza can you check this PR ? Thanks :)

2022-05-24 10:48 UTC, chienandalu approved these changes
Thanks! Tested and code looks good :+1:

2022-05-24 11:05 UTC, pedrobaeza commented
For being consistent with other existing methods and for shorten the name, I would go with `sale_coupon_criteria_order_based`

2022-05-24 11:06 UTC, francesco-ooops commented
alright, @isserver1 can you change?

2022-05-25 15:05 UTC, simahawk commented on sale_coupon_sale_order_based/tests/test_sale_coupon_sale_order_based.py
> +        partner_test = self.env["res.partner"].create(
pls set `tracking_disable=True` when creating tracked records

2022-05-25 15:05 UTC, simahawk commented on sale_coupon_sale_order_based/tests/test_sale_coupon_sale_order_based.py
> +        user_test = self.env["res.users"].create(
and set  `no_reset_password=True` too when creating users. BTW, do you really need another user?

2022-05-25 15:05 UTC, simahawk commented on sale_coupon_sale_order_based/__manifest__.py
> +{
license headers are missing everywhere ;)

2022-05-25 15:05 UTC, simahawk commented on sale_coupon_sale_order_based/__manifest__.py
> +    "application": False,
```suggestion
```

2022-05-26 18:10 UTC, GabbasovDinar commented on sale_coupon_sale_order_based/tests/test_sale_coupon_sale_order_based.py
> +        user_test = self.env["res.users"].create(
new user for the purity of the test :)

2022-05-26 18:47 UTC, GabbasovDinar commented
@simahawk done

2022-05-27 05:28 UTC, simahawk requested changes
can you squash once your done w/ the changes?

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/__manifest__.py
> +    "license": "LGPL-3",
header says AGPL, choose one :)

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/models/coupon_program.py
> +            return bool(self.env["sale.order"].search_count(domain))
as you already have the order and you are filtering by id just apply the domain on it
```suggestion
            return bool(order.filtered_domain(domain))
```

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/models/coupon_program.py
> +        """
this sounds more like a comment, I'd not override the original docstring for this

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/models/coupon_program.py
> +        """
same

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/models/coupon_program.py
> +            programs = programs and programs._filter_programs_on_order(order)
```suggestion
        if not next_order and programs:
            programs = programs._filter_programs_on_order(order)
```

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/readme/CONFIGURE.rst
> +* No configuration is required
you can trash this file

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/readme/DESCRIPTION.rst
> +Sale Coupon domain based on Sale Order values
the name comes from the manifest in generated readme

2022-05-27 05:28 UTC, simahawk commented on sale_coupon_criteria_order_based/readme/HISTORY.rst
> +14.0.1.0.0
trash this if you are not going to maintain it using towcrier

2022-05-28 15:35 UTC, GabbasovDinar commented
@simahawk ready for review

2022-05-30 14:12 UTC, simahawk approved these changes

2022-05-30 14:13 UTC, simahawk commented
/ocabot merge nobump

2022-05-30 14:25 UTC, merged