[ADD] sale_coupon_domain_free_product: New module 13.0
OCA/sale-promotion pull request #70
Opened 2022-06-23 16:39 UTC by chienandalu

This module allows to define the same reward products as the products domain. Only those products in the sale order will be rewarded.

Configuration
=============

To configure free product rewards from domains:

1. Go to *Sales > Catalog > Coupon Programs* and select or create a new one.
2. Choose the criteria of appliance you want to use and the minimum quantities, that    will be used to calculate the times the rewards can be applied.
3. On the *Reward Type* field choose *Free Product Domain*.
4. Set the proper domain and rules.
5. If you want to apply the limits for every product in the promotion limit, set the  *Strict per product limit* checkbox.

An example with the domain `[("id", "in", [1, 2])]`, strict limits and minimum quantity of 2 units:

 ===== ==================
  Qty      Products
 ===== ==================
    4   `product.product(1,)`
    2   `product.product(2,)`
    6   `product.product(3,)`
 ===== ==================

For `product.product(1,)` we'll get 2 units as reward.
For `product.product(2,)` we'll get just 1.
We'll get nothing from `product.product(3,)`

cc @Tecnativa TT37477

2022-06-24 09:03 UTC, pedrobaeza commented on sale_coupon_domain_free_product/readme/CONFIGURE.rst
> +    4   `res.product(1,)`
res.product ?

2022-06-24 09:15 UTC, chienandalu commented on sale_coupon_domain_free_product/readme/CONFIGURE.rst
> +    4   `res.product(1,)`
Ouch :man_facepalming:

2022-06-24 09:16 UTC, chienandalu commented on sale_coupon_domain_free_product/readme/CONFIGURE.rst
> +    4   `res.product(1,)`
Fixed :)

2022-07-05 06:36 UTC, cesar-tecnativa requested changes

2022-07-05 06:36 UTC, cesar-tecnativa commented on sale_coupon_domain_free_product/models/sale_coupon_reward.py
> +        res = super().name_get()
super with self - free_product_domain_promo

2022-07-24 12:00 UTC, pedrobaeza commented on sale_coupon_domain_free_product/models/sale_coupon_reward.py
> +        res = super().name_get()
@chienandalu

2022-09-05 06:28 UTC, chienandalu commented on sale_coupon_domain_free_product/models/sale_coupon_reward.py
> +        res = super().name_get()
Done

2022-09-08 19:13 UTC, pedrobaeza approved these changes

2022-09-08 19:14 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-08 19:25 UTC, merged